updated pipeline for imported clusters

diff --git a/imported/Jenkins/jenkins-pipeline b/imported/Jenkins/jenkins-pipeline
--- a/imported/Jenkins/jenkins-pipeline
+++ b/imported/Jenkins/jenkins-pipeline
@@ -27,7 +27,18 @@ pipeline {
             grep -i "cluster.rafay.dev" cluster_bootstrap.yaml > /dev/null 2>&1
             if [ $? -eq 0 ];
             then
+              set +e
+              kubectl get ns|grep rafay-system > /dev/null 2>&1
+              if [ $? -eq 1 ];
+              then
+                set -e
+                echo "namespace rafay-system not found.... applying bootstrap"
+                sleep 30
                 kubectl apply -f cluster_bootstrap.yaml
+              else
+                echo "namespace rafay-system found... cluster is already imported"
+                exit 1
+              fi
             fi
             '''
         }
